### ISSUE TITLE
有构建好的docker镜像吗

### ISSUE THREAD

**Issue by zhangzheng1212** [erda-project/erda-ui#162]
构建core模块时内存不足，已经分配到4G，有构建好的Docker 镜像吗

无法自己编译，已经设置4G内存了
![image](https://user-images.githubusercontent.com/10355077/118230152-c1510e00-b4bf-11eb-8ca2-841ef10b15f6.png)

**Comment by McDaddy** [comment]
How about other modules? Can you successfully build shell module in your local? In our development environment we only assign 2G memory for building and never get OOM error during first build.  If you are running on virtual machine please check the allocated memory for the box

**Comment by zhangzheng1212** [comment]
在wsl2中使用Windows文件系统就会出现，已解决，，希望能提供相关容器镜像，免除用户自己构建，十分感谢！

**Comment by McDaddy** [comment]
> 自己



> 在wsl2中使用Windows文件系统就会出现，已解决，，希望能提供相关容器镜像，免除用户自己构建，十分感谢！

Thanks for your feedback! Yes, your suggestion is really helpful, we're planning to provide development env image so that users could skip the build step.

**Comment by daskyrk** [comment]
Welcome to join our Dingtalk group：31232990 to follow the progress.
