### ISSUE TITLE
请教个关于config-page 组件的问题？

### ISSUE THREAD

**Issue by techbirds** [erda-project/erda-ui#2063]
配置页面上的组件如果跟后台有交互(Http 请求)，那么如何体现在配置模板里？ 

我看到`https://github.com/erda-project/erda-ui/blob/master/shell/app/config-page/mock/`下的几个案例都没有体现和后台交互的配置或者关联细节。

**Comment by laojun** [comment]
config-page需要配合后端使用
在使用场景中，请求只有一个api，前端通过配置operation，然后发起请求，由后端解析后返回新的数据。

例如：crud场景中，删除一个数据后需要刷新列表。
前端：在删除的操作上配置operation，在触发动作时向后端发起请求并传递operation数据，接受新的数据更新页面
后端：收到请求后执行对应的业务逻辑（1、删除数据库中对应数据，2、返回新的数据）

前端只需要通过operation告诉后端触发了什么操作，由后端返回这个操作之后的数据，以此来将业务逻辑转移给后端，让前端更专注样式和交互



😊  欢迎关注我们的微信公众号：尔达Erda

**Comment by techbirds** [comment]
> config-page需要配合后端使用 在使用场景中，请求只有一个api，前端通过配置operation，然后发起请求，由后端解析后返回新的数据。
> 
> 例如：crud场景中，删除一个数据后需要刷新列表。 前端：在删除的操作上配置operation，在触发动作时向后端发起请求并传递operation数据，接受新的数据更新页面 后端：收到请求后执行对应的业务逻辑（1、删除数据库中对应数据，2、返回新的数据）
> 
> 前端只需要通过operation告诉后端触发了什么操作，由后端返回这个操作之后的数据，以此来将业务逻辑转移给后端，让前端更专注样式和交互
> 
> 😊 欢迎关注我们的微信公众号：尔达Erda

感谢回答。

还是有几个困惑：

1、"前端通过operation告诉后端触发了操作" 是怎么告诉后台的？是发HTTP请求的吗？这部分配置难道是在应用运行时关联的吗？视图对应的操作接口不应该是和视图模板关联的吗？

![image](https://user-images.githubusercontent.com/3411696/142628868-519fd6f6-c5c4-4245-8f1f-5bc43872e167.png)

**Comment by daskyrk** [comment]
@techbirds 我们的协议（内部叫组件化协议）封装了页面的操作，以 add task 流程为例，打开创建表单是一个 click operation，只改变前端表单组件状态，和后端无请求交互。用户填写完点击保存也是一个click operation，会和后端有交互，协议会将操作（create）和上下文信息（如 formData）等，通过 HTTP 请求（是统一的一个接口）发送给后端，后端知道用户是触发了 create 这个动作，并且拿到了要保存的数据，再调用 API （例如 /api/task/create）去保存数据到数据库。
这个流程中，页面其实不关心哪个操作要调用哪个后端 API，和后端的交互都是抽象成了一个个的 operation，所以 mock 下的场景数据没有 API 相关的任何配置。不知道是否解答了你的疑惑？

**Comment by laojun** [comment]
1、“前端通过operation告诉后端触发了操作" 是怎么告诉后台的？是发HTTP请求的吗？这部分配置难道是在应用运行时关联的吗？视图对应的操作接口不应该是和视图模板关联的吗？

举个栗子
1、第一次请求
request: /api/protocol/render
send: {scenario:'user-manage'}  //  请求告诉后端需要获取user-manage这个场景的初始化数据
response
```
{
...
userTable: {
   data: [
        { 
           id: 1, 
           name: 'a', 
           operation: { key: 'deleteMe',  meta: {deleteId: 1 } } ,} 
             // operation是协议的一部分，由后端返回，当前端用户操作了这个动作，就会发送一次请求
    ]
  }
}
```
2、点击删除
request:  /api/protocol/render // 同一个接口
send: { scenario:'user-manage', event: { key: 'deleteMe', meta: {deleteId: 2} }} // 将触发的操作原封不动传给后端
response: 
```
{
  userTable: {
      data: [], //返回删除后的数据
   }
}
```


同理，添加会有一个formModal组件，上面有个submit的operation，提交后，会把这个协议回传，后端可以从组件的state中获取到用户填入的数据，然后通过operation，得知需要添加这个表单中的数据

request: /api/protocol/render
send: 
```
{
   scenario:'user-manage',
   event: {
        key: 'addUser',
        meta: {
             username: 'xxxx' // 其中这里的数据可以在表单组件中，用户触发submit时，当做payload传给协议  
        }
    }
    
}

```

**Comment by techbirds** [comment]
> @techbirds 我们的协议（内部叫组件化协议）封装了页面的操作，以 add task 流程为例，打开创建表单是一个 click operation，只改变前端表单组件状态，和后端无请求交互。用户填写完点击保存也是一个click operation，会和后端有交互，协议会将操作（create）和上下文信息（如 formData）等，通过 HTTP 请求（是统一的一个接口）发送给后端，后端知道用户是触发了 create 这个动作，并且拿到了要保存的数据，再调用 API （例如 /api/task/create）去保存数据到数据库。 这个流程中，页面其实不关心哪个操作要调用哪个后端 API，和后端的交互都是抽象成了一个个的 operation，所以 mock 下的场景数据没有 API 相关的任何配置。不知道是否解答了你的疑惑？

非常感谢，说的很明白！

**Comment by techbirds** [comment]
> 1、“前端通过operation告诉后端触发了操作" 是怎么告诉后台的？是发HTTP请求的吗？这部分配置难道是在应用运行时关联的吗？视图对应的操作接口不应该是和视图模板关联的吗？
> 
> 举个栗子 1、第一次请求 request: /api/protocol/render send: {scenario:'user-manage'} // 请求告诉后端需要获取user-manage这个场景的初始化数据 response
> 
> ```
> {
> ...
> userTable: {
>    data: [
>         { 
>            id: 1, 
>            name: 'a', 
>            operation: { key: 'deleteMe', text: '删除用户',  meta: {deleteId: 1 } } ,} 
>              // operation是协议的一部分，由后端返回，前端会先在table中渲染一个'删除用户'的操作按钮，当前端用户操作了这个动作，就会发送一次请求
>     ]
>   }
> }
> ```
> 
> 2、点击删除 request: /api/protocol/render // 同一个接口 send: { scenario:'user-manage', event: { key: 'deleteMe', meta: {deleteId: 1} }} // 将触发的操作原封不动传给后端 // 此处后端会自行调用下层的原生接口 比如先调用 api/delete/1, 再调用 api/search，然后将新的数据返回，但前端不感知 response:
> 
> ```
> {
>   userTable: {
>       data: [], //返回删除后的数据
>    }
> }
> ```
> 
> 同理，添加会有一个formModal组件，上面有个submit的operation，提交后，会把这个协议回传，前端可以通过event告诉后端做了什么 request: /api/protocol/render send:
> 
> ```
> {
>    scenario:'user-manage',
>    event: {
>         key: 'addUser',
>         meta: {
>              username: 'xxxx' // 其中这里的数据可以在表单组件中，用户触发submit时，当做payload传给协议  
>         }
>     }
>     
> }
> ```

非常感谢！理解了。
