### ISSUE TITLE
erda-ui init 命令无法执行

### ISSUE THREAD

**Issue by njxz** [erda-project/erda-ui#2370]
操作系统： Red Hat 4.8.5
node 版本: v6.17.1

git clone下erda-ui项目后，跟着README下的命令时出现问题

![图片](https://user-images.githubusercontent.com/16254670/147184347-2e35043a-8020-4aac-a5e9-e0edab112e7e.png)

![图片](https://user-images.githubusercontent.com/16254670/147184376-d9c6840a-0398-4e6d-ac7d-23635b32acb3.png)

**Comment by McDaddy** [comment]
@njxz 目前erda-ui能支持的node版本最低为v12。请升级node版本之后再试一下

**Comment by njxz** [comment]
node 更新后没问题了
