### ISSUE TITLE
npm run watch发生报错

### ISSUE THREAD

**Issue by njxz** [erda-project/erda-ui#2611]
根据readme,成功运行完成
```shell
	npm i @erda-ui/cli -g
	erda-ui init
        #core目录
       	npm run build
        # shell目录
        npm run watch
```
在运行`npm run watch`的时候提
![npm run build error](https://user-images.githubusercontent.com/16254670/149289991-6768a522-b6ba-46f6-aa5b-8ab8cc70e10c.png)
示module not found

**Comment by McDaddy** [comment]
@njxz 是否已经更新到最新的master分支？

**Comment by njxz** [comment]
为一周前版本，正在尝试 更新后再试

**Comment by njxz** [comment]
npm run build中的build 这样算成功吗

**Comment by njxz** [comment]
@McDaddy

**Comment by McDaddy** [comment]
> npm run build中的build 这样算成功吗

是的，build core是成功的

**Comment by njxz** [comment]
![图片](https://user-images.githubusercontent.com/16254670/149304640-dd8495df-e6ba-4b83-adc0-a83c4f02be51.png)

这一段也是成功的吗

**Comment by njxz** [comment]
![图片](https://user-images.githubusercontent.com/16254670/149306485-fe76bf6a-dfe9-4a28-9ffd-4e066d68d5f3.png)

**Comment by njxz** [comment]
@McDaddy  已经解决，非常感谢
