### ISSUE TITLE
1.5版本报错

### ISSUE THREAD

**Issue by njxz** [erda-project/erda-ui#2805]
原先是直接运行的master版本的erda-ui，通过npm start没有问题。
通过git chekcout到1.5版本的web-ui之后，通过npm start 打开后，通过浏览器访问提示
![图片](https://user-images.githubusercontent.com/16254670/150739323-d6a286f7-5786-4daa-bed8-350ee723abdb.png)

**Comment by daskyrk** [comment]
请问你是在 scheduler 目录下执行的 `npm run start` 是吗？这样会运行在开发模式。
开发模式下我们使用自签名证书来访问 https 的 ui 域名，在 chrome 下可以通过在界面上直接输入 `thisisunsafe` 忽略警告，但还没有试过在 firefox 下面如何忽略警告。如果用 chrome 可以，说明是浏览器的限制，需要查一下 firefox 是否可以忽视这个警告。

**Comment by njxz** [comment]
> 请问你是在 scheduler 目录下执行的 `npm run start` 是吗？这样会运行在开发模式。 开发模式下我们使用自签名证书来访问 https 的 ui 域名，在 chrome 下可以通过在界面上直接输入 `thisisunsafe` 忽略警告，但还没有试过在 firefox 下面如何忽略警告。如果用 chrome 可以，说明是浏览器的限制，需要查一下 firefox 是否可以忽视这个警告。

下载chrome后，通过`thisisunsafe`成功登录。请问下这个可以通过什么方式避免吗 我看1.6版本是已经没有这个问题了

**Comment by daskyrk** [comment]
> 

你说的避免是指在 chrome 下不用输入 `thisisunsafe`, 还是在 firefox 下也可以访问？

**Comment by njxz** [comment]
出了个新的问题，登录后跳转到了`.env`中设置的页面，而不是本地的测试UI
`.env`配置如下
```yaml
BACKEND_URL=https://erda.io
UC_BACKEND_URL=https://erda.io
MODULES=core,shell,market,uc,admin,fdp
SCHEDULER_PORT=8000
SCHEDULER_URL=https://local.erda.io
```

**Comment by njxz** [comment]
> > 
> 
> 你说的避免是指在 chrome 下不用输入 `thisisunsafe`, 还是在 firefox 下也可以访问？

是想避免 输入`thisisunsafe`

**Comment by daskyrk** [comment]
`.env` 中的配置只给 ui 的 scheduler 用，登录时重定向的地址是在 https://github.com/erda-project/erda/blob/master/quick-start/kratos/kratos.yml#L45 中配置的

**Comment by daskyrk** [comment]
> > > 
> > 
> > 
> > 你说的避免是指在 chrome 下不用输入 `thisisunsafe`, 还是在 firefox 下也可以访问？
> 
> 是想避免 输入`thisisunsafe`

这个没法避免，1.6 没有这个问题估计是因为浏览器在一段时间里不会重复检查，这方面没有代码层面的变化。

**Comment by njxz** [comment]
> 

好的

**Comment by njxz** [comment]
非常感谢大佬解答 @daskyrk
