### ISSUE TITLE
初始化界面时，应该使用骨架屏填充

### ISSUE THREAD

**Issue by Sky-shang** [erda-project/erda-ui#747]
![微信图片_20210726152235](https://user-images.githubusercontent.com/29321889/126949150-0b63ba61-7ec9-49f2-a7bd-fec5a20d26db.png)

**Comment by daskyrk** [comment]
是的，安排上，数据返回前展示一个列表占位组件。 @sherotree

**Comment by Sky-shang** [comment]
nice
