### ISSUE TITLE
redundant scrollbars 

### ISSUE THREAD

**Issue by Zhuangkh** [erda-project/erda-ui#748]
## Current Behavior

In the current version, scrollbars appear in some screens that should not be there. For example, the sidebar and the table header of the `code quality access control`.

![image](https://user-images.githubusercontent.com/30818313/126950569-d6de2e4c-0fff-47ba-82aa-c0972d2862f5.png)

## Context

Fix the style for better user experience.

## Your Environment

* Browser Name and version: `Microsoft Edge Version 92.0.902.55 (Official build) (64-bit)` & `Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)`
* Operating System and version (desktop or mobile): win10 19043.1110

**Comment by daskyrk** [comment]
cc @sherotree

**Comment by daskyrk** [comment]
Can not reproduce, close for now and feel free to reopen.
