### ISSUE TITLE
Erda dashboard value view problem

### ISSUE THREAD

**Issue by luoyuctl** [erda-project/erda-ui#946]
#### What happened:
 when value below 0.005 percent, dashboard value round down view will not be readable. 
![image](https://user-images.githubusercontent.com/51604064/129481399-89edcdfa-4e59-4990-be52-87dc63392f9d.png)

#### What you expected to happen:
round down like 0.00 or other readable type.

#### Environment:
- Erda Cloud

**Comment by daskyrk** [comment]
Round down to 0 @sherotree

**Comment by sherotree** [comment]
https://github.com/erda-project/erda-ui/pull/1012
